# Preconditions
- name: Update APT Cache
  apt:
    update_cache: yes
- name: Remove old docker.io
  apt:
    name: docker.io
    state: absent
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
- name: Install ca-certificates
  apt:
    name: ca-certificates
- name: Install curl
  apt:
    name: curl
- name: Install software-properties-common
  apt:
    name: software-properties-common

# Add Repo and install docker
- name: Add docker apt keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
- name: update apt
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
    state: present
- name: Install docker
  apt:
    name: docker-ce
    update_cache: yes
