# Preconditions
- name: Update APT Cache
  apt:
    update_cache: yes
- name: Remove old docker.io
  apt:
    name: docker.io
    state: absent
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
- name: Install ca-certificates
  apt:
    name: ca-certificates
- name: Install software-properties-common
  apt:
    name: software-properties-common

# Add Repo and install docker
- name: Add docker apt keys
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: update apt
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
- name: Install docker
  apt:
    name: docker-ce
    update_cache: yes
